version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: synect-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: synect_user
      POSTGRES_PASSWORD: synect_password
      POSTGRES_DB: synect_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
